import type {Metadata} from "next";
import {Inter, Inter_Tight} from "next/font/google";
import "./globals.css";
import React from "react";

const primaryFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const secondaryFont = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }:
  Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html
      lang="pt-br"
      className={`${primaryFont.variable} ${secondaryFont.variable} h-full antialiased`}
    >
    <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
